import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const GIT_DIR = path.join(__dirname, '..', '.git');
const HOOKS_DIR = path.join(GIT_DIR, 'hooks');

async function setup() {
  try {
    const gitExists = await fs.stat(GIT_DIR).catch(() => null);
    if (!gitExists || !gitExists.isDirectory()) {
      console.log('Not a git repository, skipping pre-commit hook setup.');
      return;
    }

    await fs.mkdir(HOOKS_DIR, { recursive: true });
    
    const preCommitPath = path.join(HOOKS_DIR, 'pre-commit');
    const hookScript = `#!/bin/sh
# Auto-generated by RepoTracker scripts/setup-hooks.js
echo "Running Gitleaks check..."
gitleaks protect -v --staged
if [ $? -eq 1 ]; then
  echo "Gitleaks detected secrets in your staged changes. Commit aborted."
  exit 1
fi
`;

    await fs.writeFile(preCommitPath, hookScript, { mode: 0o755 });
    console.log('✅ Installed pre-commit secret scanner (gitleaks) hook.');
  } catch (err) {
    console.warn('⚠️ Failed to setup pre-commit hook:', err.message);
  }
}

setup();
